import { db } from './db';

/**
 * Mark room as dirty after guest checkout.
 * Also auto-creates a high-priority cleaning task.
 * Call this from booking checkout logic.
 */
export async function markRoomDirtyAfterCheckout(roomId: string, tenantId: string, bookingId?: string) {
  try {
    // Fetch room with property info before updating
    const room = await db.room.findUnique({
      where: { id: roomId },
      include: { property: { select: { id: true, name: true } } },
    });

    if (!room) {
      console.error(`[HK Automation] Room ${roomId} not found`);
      return false;
    }

    // Update room housekeeping status to dirty
    await db.room.update({
      where: { id: roomId },
      data: { housekeepingStatus: 'dirty' },
    });

    // Check if there's already an active checkout cleaning task for this room
    const existingTask = await db.task.findFirst({
      where: {
        roomId,
        type: 'cleaning',
        category: 'checkout',
        status: { in: ['pending', 'in_progress', 'assigned'] },
      },
    });

    if (existingTask) {
      console.log(`[HK Automation] Active checkout task ${existingTask.id} already exists for room ${room.number}`);
      return true;
    }

    // Auto-create a high-priority checkout cleaning task
    await db.task.create({
      data: {
        tenantId,
        propertyId: room.propertyId,
        roomId,
        type: 'cleaning',
        category: 'checkout',
        title: `Auto: Checkout Clean - Room ${room.number}`,
        description: [
          'Automatic task created after guest checkout.',
          'Full cleaning required including:',
          '- Strip and replace all linens',
          '- Clean and sanitize bathroom',
          '- Dust all surfaces',
          '- Vacuum/sweep/mop floors',
          '- Restock amenities and supplies',
          '- Check for damages',
        ].join('\n'),
        priority: 'high',
        status: 'pending',
        scheduledAt: new Date(),
        estimatedDuration: 45,
        roomStatusBefore: 'occupied',
        roomStatusAfter: 'dirty',
        notes: bookingId ? `Triggered by booking ${bookingId}` : 'Auto-generated by checkout automation',
      },
    });

    console.log(`[HK Automation] Created checkout cleaning task for room ${room.number}`);
    return true;
  } catch (error) {
    console.error('[HK Automation] Failed to mark room dirty after checkout:', error);
    return false;
  }
}

/**
 * Complete a cleaning task and move room to inspected status.
 * Runs in a transaction to ensure consistency.
 */
export async function completeCleaningAndInspect(roomId: string, taskId: string, userId: string) {
  try {
    await db.$transaction(async (tx) => {
      // Update task as completed
      await tx.task.update({
        where: { id: taskId },
        data: {
          status: 'completed',
          completedAt: new Date(),
        },
      });

      // Move room to inspected status
      await tx.room.update({
        where: { id: roomId },
        data: {
          housekeepingStatus: 'inspected',
          lastCleanedAt: new Date(),
          lastInspectedAt: new Date(),
          inspectedBy: userId,
        },
      });

      // Clear the current task reference on the room
      await tx.room.update({
        where: { id: roomId },
        data: { currentTaskId: null },
      });
    });

    console.log(`[HK Automation] Completed cleaning task ${taskId} for room ${roomId}, moved to inspected`);
    return true;
  } catch (error) {
    console.error('[HK Automation] Failed to complete cleaning and inspect:', error);
    return false;
  }
}

/**
 * Inspect a room and mark as available/clean.
 * Called after a supervisor confirms the room passes inspection.
 */
export async function inspectAndReleaseRoom(roomId: string, userId: string, qualityScore?: number) {
  try {
    await db.room.update({
      where: { id: roomId },
      data: {
        housekeepingStatus: 'clean',
        lastInspectedAt: new Date(),
        inspectedBy: userId,
        status: 'available',
        currentTaskId: null,
      },
    });

    console.log(`[HK Automation] Room ${roomId} inspected and released by ${userId}, score: ${qualityScore ?? 'N/A'}`);
    return true;
  } catch (error) {
    console.error('[HK Automation] Failed to inspect and release room:', error);
    return false;
  }
}

/**
 * Auto-assign a task to the least busy staff member with matching skills.
 */
export async function autoAssignTask(taskId: string) {
  try {
    const task = await db.task.findUnique({
      where: { id: taskId },
      include: { room: { select: { propertyId: true } } },
    });

    if (!task || task.assignedTo) {
      return null; // Already assigned or not found
    }

    // Find staff with lowest workload for today
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const workloads = await db.staffWorkload.findMany({
      where: {
        date: { gte: today },
        tenantId: task.tenantId,
        propertyId: task.room?.propertyId,
      },
      orderBy: { workedMinutes: 'asc' },
    });

    if (workloads.length === 0) {
      console.log(`[HK Automation] No staff workload entries found for auto-assignment of task ${taskId}`);
      return null;
    }

    // Fetch user data for the best fit workload
    const bestFit = workloads[0];
    const bestFitUser = await db.user.findUnique({
      where: { id: bestFit.userId },
      select: { id: true, firstName: true, lastName: true },
    });

    const assigned = await db.task.update({
      where: { id: taskId },
      data: {
        assignedTo: bestFit.userId,
        status: 'assigned',
      },
    });

    console.log(`[HK Automation] Auto-assigned task ${taskId} to ${bestFitUser?.firstName ?? 'Unknown'} ${bestFitUser?.lastName ?? ''}`);
    return assigned;
  } catch (error) {
    console.error('[HK Automation] Failed to auto-assign task:', error);
    return null;
  }
}

/**
 * Generate recurring task instances from completed recurring tasks.
 * Called by the cron scheduler.
 */
export async function generateRecurringTasks() {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  let created = 0;

  try {
    const recurringTasks = await db.task.findMany({
      where: {
        isRecurring: true,
        status: 'completed',
        recurrenceRule: { not: null },
      },
    });

    for (const task of recurringTasks) {
      if (!task.recurrenceRule || !task.completedAt) continue;

      let shouldCreate = false;
      const rule = JSON.parse(task.recurrenceRule);
      const lastCompleted = new Date(task.completedAt);
      const daysSinceCompletion = Math.floor(
        (today.getTime() - lastCompleted.getTime()) / (1000 * 60 * 60 * 24)
      );

      switch (rule.frequency) {
        case 'daily':
          shouldCreate = daysSinceCompletion >= 1;
          break;
        case 'weekly':
          shouldCreate = daysSinceCompletion >= 7;
          break;
        case 'monthly':
          shouldCreate = daysSinceCompletion >= 30;
          break;
        case 'quarterly':
          shouldCreate = daysSinceCompletion >= 90;
          break;
        case 'yearly':
          shouldCreate = daysSinceCompletion >= 365;
          break;
      }

      if (shouldCreate) {
        await db.task.create({
          data: {
            tenantId: task.tenantId,
            propertyId: task.propertyId,
            roomId: task.roomId,
            assignedTo: task.assignedTo,
            type: task.type,
            category: task.category,
            title: task.title,
            description: task.description,
            priority: task.priority,
            status: 'pending',
            scheduledAt: today,
            estimatedDuration: task.estimatedDuration,
            isRecurring: true,
            recurrenceRule: task.recurrenceRule,
            createdBy: task.createdBy,
            deadline: rule.deadlineOffsetDays
              ? new Date(today.getTime() + rule.deadlineOffsetDays * 24 * 60 * 60 * 1000)
              : undefined,
          },
        });
        created++;
      }
    }
  } catch (error) {
    console.error('[HK Automation] Recurring task generation failed:', error);
    throw error;
  }

  return { created, totalChecked: created };
}

/**
 * Check for overdue preventive maintenance items and auto-create tasks.
 * Called by the cron scheduler.
 */
export async function checkOverduePreventiveMaintenance() {
  const now = new Date();
  let created = 0;
  let overdueCount = 0;

  try {
    const overdueItems = await db.preventiveMaintenance.findMany({
      where: {
        nextDueAt: { lte: now },
        status: 'active',
      },
      include: { property: { select: { id: true, tenantId: true } } },
    });

    overdueCount = overdueItems.length;

    for (const pm of overdueItems) {
      // Prevent duplicate tasks - check within last 7 days
      const existingTask = await db.task.findFirst({
        where: {
          title: { contains: pm.title },
          type: 'maintenance',
          status: { in: ['pending', 'in_progress', 'assigned'] },
          createdAt: { gte: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000) },
        },
      });

      if (existingTask) {
        continue;
      }

      // Parse checklist for description
      let checklistItems: string[] = [];
      try {
        checklistItems = JSON.parse(pm.checklist || '[]');
      } catch {
        checklistItems = [];
      }

      await db.task.create({
        data: {
          tenantId: pm.tenantId,
          propertyId: pm.propertyId,
          type: 'maintenance',
          category: 'preventive',
          title: `[PM] ${pm.title}`,
          description: [
            `Preventive maintenance: ${pm.description || pm.title}`,
            `Frequency: ${pm.frequency}`,
            checklistItems.length > 0
              ? `\nChecklist:\n${checklistItems.map((item) => `- ${item}`).join('\n')}`
              : '',
          ].join('\n'),
          priority: pm.priority || 'medium',
          status: 'pending',
          scheduledAt: now,
          estimatedDuration: pm.estimatedDuration,
        },
      });

      // Update next due date based on frequency
      let nextDue: Date | null = null;
      const ms = 24 * 60 * 60 * 1000;
      switch (pm.frequency) {
        case 'daily':
          nextDue = new Date(now.getTime() + 1 * ms);
          break;
        case 'weekly':
          nextDue = new Date(now.getTime() + 7 * ms);
          break;
        case 'monthly':
          nextDue = new Date(now.getTime() + 30 * ms);
          break;
        case 'quarterly':
          nextDue = new Date(now.getTime() + 90 * ms);
          break;
        case 'yearly':
          nextDue = new Date(now.getTime() + 365 * ms);
          break;
      }

      if (nextDue) {
        await db.preventiveMaintenance.update({
          where: { id: pm.id },
          data: {
            lastCompletedAt: now,
            nextDueAt: nextDue,
          },
        });
      }

      created++;
    }
  } catch (error) {
    console.error('[HK Automation] PM auto-trigger failed:', error);
    throw error;
  }

  return { overdue: overdueCount, created };
}
