import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { db } from '@/lib/db';
import { randomBytes } from 'crypto';

// POST: Generate a secure portal token for a booking
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.tenantId) {
      return NextResponse.json(
        { success: false, error: { message: 'Unauthorized' } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { bookingId, expiresInHours = 72 } = body;

    if (!bookingId) {
      return NextResponse.json(
        { success: false, error: { message: 'Booking ID is required' } },
        { status: 400 }
      );
    }

    // Find the booking and verify tenant
    const booking = await db.booking.findFirst({
      where: { 
        id: bookingId,
        tenantId: session.user.tenantId,
      },
      include: {
        primaryGuest: true,
        roomType: true,
        room: true,
      },
    });

    if (!booking) {
      return NextResponse.json(
        { success: false, error: { message: 'Booking not found' } },
        { status: 404 }
      );
    }

    // Generate secure token
    const token = randomBytes(32).toString('hex');
    const expiresAt = new Date();
    expiresAt.setHours(expiresAt.getHours() + expiresInHours);

    // Update booking with portal token
    const updatedBooking = await db.booking.update({
      where: { id: bookingId },
      data: {
        portalToken: token,
        portalTokenExpires: expiresAt,
        preArrivalLink: `/portal/${token}`,
        preArrivalSent: true,
      },
    });

    // Create audit log
    await db.bookingAuditLog.create({
      data: {
        bookingId: booking.id,
        action: 'portal_token_generated',
        notes: `Portal token generated by ${session.user.email}. Expires: ${expiresAt.toISOString()}`,
        performedBy: session.user.id,
      },
    });

    return NextResponse.json({
      success: true,
      data: {
        token,
        portalUrl: `/portal/${token}`,
        expiresAt,
      },
    });
  } catch (error) {
    console.error('Error generating portal token:', error);
    return NextResponse.json(
      { success: false, error: { message: 'Failed to generate portal token' } },
      { status: 500 }
    );
  }
}

// GET: Validate token and get booking details (PUBLIC - token-based auth)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const token = searchParams.get('token');

    if (!token) {
      return NextResponse.json(
        { success: false, error: { message: 'Token is required' } },
        { status: 400 }
      );
    }

    // Validate token format (should be 64 hex characters)
    if (!/^[a-f0-9]{64}$/i.test(token)) {
      return NextResponse.json(
        { success: false, error: { message: 'Invalid token format' } },
        { status: 400 }
      );
    }

    // Find booking by portal token
    const booking = await db.booking.findFirst({
      where: {
        portalToken: token,
        deletedAt: null,
      },
      include: {
        primaryGuest: {
          include: {
            documents: true,
          },
        },
        roomType: {
          include: {
            property: true,
          },
        },
        room: true,
        folios: {
          where: { status: { not: 'paid' } },
          include: {
            lineItems: true,
            payments: {
              where: { status: 'completed' },
            },
          },
        },
      },
    });

    if (!booking) {
      return NextResponse.json(
        { success: false, error: { message: 'Invalid or expired token' } },
        { status: 404 }
      );
    }

    // Check if token is expired
    if (booking.portalTokenExpires && new Date() > booking.portalTokenExpires) {
      return NextResponse.json(
        { success: false, error: { message: 'Portal link has expired' } },
        { status: 410 }
      );
    }

    // Calculate payment status
    const totalBilled = booking.folios.reduce((sum, folio) => sum + folio.totalAmount, 0);
    const totalPaid = booking.folios.reduce((sum, folio) => {
      return sum + folio.payments.reduce((pSum, p) => pSum + p.amount, 0);
    }, 0);
    const balanceDue = totalBilled - totalPaid;

    // Parse preferences
    let preferences = {};
    try {
      preferences = booking.preferences ? JSON.parse(booking.preferences) : {};
    } catch {
      preferences = {};
    }

    // Check KYC document status
    const kycDocuments = booking.primaryGuest.documents || [];
    const verifiedDocuments = kycDocuments.filter(d => d.status === 'verified').length;
    const pendingDocuments = kycDocuments.filter(d => d.status === 'pending').length;

    return NextResponse.json({
      success: true,
      data: {
        booking: {
          id: booking.id,
          confirmationCode: booking.confirmationCode,
          checkIn: booking.checkIn,
          checkOut: booking.checkOut,
          adults: booking.adults,
          children: booking.children,
          infants: booking.infants,
          roomRate: booking.roomRate,
          totalAmount: booking.totalAmount,
          currency: booking.currency,
          status: booking.status,
          specialRequests: booking.specialRequests,
          kycRequired: booking.kycRequired,
          kycCompleted: booking.kycCompleted,
          kycStatus: booking.kycStatus,
          eSignedAt: booking.eSignedAt,
          preArrivalCompleted: booking.preArrivalCompleted,
        },
        guest: {
          id: booking.primaryGuest.id,
          firstName: booking.primaryGuest.firstName,
          lastName: booking.primaryGuest.lastName,
          email: booking.primaryGuest.email,
          phone: booking.primaryGuest.phone,
          nationality: booking.primaryGuest.nationality,
          dateOfBirth: booking.primaryGuest.dateOfBirth,
          gender: booking.primaryGuest.gender,
          idType: booking.primaryGuest.idType,
          idNumber: booking.primaryGuest.idNumber,
          address: booking.primaryGuest.address,
          city: booking.primaryGuest.city,
          country: booking.primaryGuest.country,
          postalCode: booking.primaryGuest.postalCode,
          kycStatus: booking.primaryGuest.kycStatus,
          preferences: booking.primaryGuest.preferences,
          dietaryRequirements: booking.primaryGuest.dietaryRequirements,
        },
        documents: kycDocuments.map(doc => ({
          id: doc.id,
          type: doc.type,
          name: doc.name,
          status: doc.status,
          expiryDate: doc.expiryDate,
          createdAt: doc.createdAt,
        })),
        roomType: {
          id: booking.roomType.id,
          name: booking.roomType.name,
          description: booking.roomType.description,
          maxAdults: booking.roomType.maxAdults,
          maxChildren: booking.roomType.maxChildren,
          amenities: booking.roomType.amenities,
          property: booking.roomType.property ? {
            id: booking.roomType.property.id,
            name: booking.roomType.property.name,
            address: booking.roomType.property.address,
            city: booking.roomType.property.city,
            checkInTime: booking.roomType.property.checkInTime,
            checkOutTime: booking.roomType.property.checkOutTime,
          } : null,
        },
        room: booking.room ? {
          id: booking.room.id,
          number: booking.room.number,
          floor: booking.room.floor,
          digitalKeyEnabled: booking.room.digitalKeyEnabled,
        } : null,
        payment: {
          totalBilled,
          totalPaid,
          balanceDue,
          currency: booking.currency,
        },
        preferences,
        kycProgress: {
          total: kycDocuments.length,
          verified: verifiedDocuments,
          pending: pendingDocuments,
          isComplete: booking.kycCompleted,
        },
        steps: {
          guestDetails: !!(booking.primaryGuest.email && booking.primaryGuest.phone),
          kycDocuments: booking.kycCompleted || verifiedDocuments > 0,
          preferences: Object.keys(preferences).length > 0,
          eSignature: !!booking.eSignedAt,
          payment: balanceDue <= 0,
        },
      },
    });
  } catch (error) {
    console.error('Error validating portal token:', error);
    return NextResponse.json(
      { success: false, error: { message: 'Failed to validate token' } },
      { status: 500 }
    );
  }
}
