const sectionMap: Record<string, () => Promise<{ default: React.ComponentType<any> }>> = {
  'settings-gdpr': () => import('@/components/gdpr/gdpr-manager'),
  'admin-gdpr': () => import('@/components/gdpr/gdpr-manager'),
  'gdpr-compliance': () => import('@/components/gdpr/gdpr-manager'),
  'automation-workflow': () => import('@/components/automation/workflow-builder'),
  'automation-workflows': () => import('@/components/automation/workflow-builder'),
  'automation-rules': () => import('@/components/automation/rules-engine'),
  'automation-templates': () => import('@/components/automation/templates'),
  'automation-logs': () => import('@/components/automation/execution-logs'),
  'integrations-payment': () => import('@/components/integrations/payment-gateways-page'),
  'integrations-payments': () => import('@/components/integrations/payment-gateways-page'),
  'integrations-wifi': () => import('@/components/integrations/wifi-gateways'),
  'integrations-pos': () => import('@/components/integrations/pos-systems'),
  'integrations-apis': () => import('@/components/integrations/third-party-apis'),
  'notifications-templates': () => import('@/components/notifications/templates'),
  'notifications-logs': () => import('@/components/notifications/delivery-logs'),
  'notifications-settings': () => import('@/components/notifications/settings'),
  'webhooks-events': () => import('@/components/webhooks/events'),
  'webhooks-delivery': () => import('@/components/webhooks/delivery'),
  'webhooks-retry': () => import('@/components/webhooks/retry-queue'),
  'ai-copilot': () => import('@/components/ai/copilot'),
  'ai-provider': () => import('@/components/ai/provider-settings'),
  'ai-settings': () => import('@/components/ai/provider-settings'),
  'ai-insights': () => import('@/components/ai/insights'),
  'help-center': () => import('@/components/help/help-center-landing'),
  'help-articles': () => import('@/components/help/articles-library'),
  'help-tutorials': () => import('@/components/help/tutorial-progress-page'),
  'profile': () => import('@/components/profile/user-profile'),
  'profile-user': () => import('@/components/profile/user-profile'),
  'ui-showcase': () => import('@/components/showcase/ui-style-showcase'),
  'ads-campaigns': () => import('@/components/ads/ad-campaigns'),
  'ads-google': () => import('@/components/ads/google-hotel-ads'),
  'ads-performance': () => import('@/components/ads/performance-tracking'),
  'ads-roi': () => import('@/components/ads/roi-analytics'),
};

export const otherMap = sectionMap;
