const sectionMap: Record<string, () => Promise<{ default: React.ComponentType<any> }>> = {
  'wifi-sessions': () => import('@/components/wifi/sessions'),
  'wifi-vouchers': () => import('@/components/wifi/vouchers'),
  'wifi-plans': () => import('@/components/wifi/plans'),
  'wifi-logs': () => import('@/components/wifi/usage-logs'),
  'wifi-gateway': () => import('@/components/wifi/gateway-integration'),
  'wifi-aaa': () => import('@/components/wifi/aaa-config'),
  'wifi-network': () => import('@/components/wifi/network-page'),
  'wifi-dhcp': () => import('@/components/wifi/dhcp-page'),
  'wifi-portal': () => import('@/components/wifi/portal-page'),
  'wifi-firewall': () => import('@/components/wifi/firewall-page'),
  'wifi-reports': () => import('@/components/wifi/reports-page'),
  'wifi-access': () => import('@/components/wifi/wifi-access-page'),
  'wifi-gateway-radius': () => import('@/components/wifi/gateway-radius-page'),
  'wifi-dns': () => import('@/components/wifi/dns-page'),
  'wifi-concurrent-sessions': () => import('@/components/wifi/concurrent-sessions'),
  'wifi-provisioning-logs': () => import('@/components/wifi/provisioning-logs'),
  'wifi-bandwidth-scheduler': () => import('@/components/wifi/bandwidth-scheduler'),
  'wifi-content-filter': () => import('@/components/wifi/content-filter'),
  'wifi-mac-auth': () => import('@/components/wifi/mac-auth'),
  'wifi-portal-whitelist': () => import('@/components/wifi/portal-whitelist'),
  'wifi-auth-logs': () => import('@/components/wifi/auth-logs'),
  'wifi-print-card': () => import('@/components/wifi/print-card'),
  'wifi-event-wifi': () => import('@/components/wifi/event-wifi'),
  'wifi-live-sessions': () => import('@/components/wifi/live-sessions'),
  'wifi-coa-audit': () => import('@/components/wifi/coa-audit'),
  'wifi-fap-policies': () => import('@/components/wifi/fap-policies'),
  'wifi-web-categories': () => import('@/components/wifi/web-categories'),
  'wifi-user-status-history': () => import('@/components/wifi/user-status-history'),
  'wifi-nas-health': () => import('@/components/wifi/nas-health'),
  'wifi-bw-policy-details': () => import('@/components/wifi/bw-policy-details'),
};

export const wifiMap = sectionMap;
